### ISSUE TITLE
Persistant candle problem

### ISSUE THREAD

**Issue by SheMaster** [GimmerBot/Gimmer#84] opened 2018-05-31 19:41 UTC
#### Specifications
 - Gimmer Version: v0.2.12
 - OS: mac os 10.13.4
 - Date: 31.5.2018
 
#### Printscreen (Case needed)
![screen shot 2018-05-31 at 20 20 53](https://user-images.githubusercontent.com/39347962/40804338-42622792-651b-11e8-9f22-48c5eeab159f.png)

**Comment by Flllexa** [comment] 2018-05-31 22:46
This was fixed in 0.2.13 version, thanks SheMaster ;)

**Closed by Flllexa** 2018-05-31 22:46 UTC
Labels: Category: Backend, Platform: All, Priority : High, Status: Fixed/Solved, Type: Bug

**Comment by modem7** [comment] 2018-05-31 23:17
![capture](https://user-images.githubusercontent.com/4349962/40813109-1a1dda90-6531-11e8-8bab-376c93c72673.JPG)

The issue is still occurring in 0.2.13 unfortunately.
