### ISSUE TITLE
MACD signals aren't same as TV chart

### ISSUE THREAD

**Issue by ficovolante** [GimmerBot/Gimmer#89] opened 2018-06-02 10:16 UTC
#### Expected Behaviour
I've been trying to correlate the MACD buy/sell signals with the TV chart of the MACD and I can't. It would be good to understand what you intend the bahaviour to be. Is it:
a) Buy when MACD crosses signal from below 
b) Buy when MACD goes positive (short-term EMA greater than long-term EMA) - probably not as this would be the same as an EMA-cross.
[Investopedia MACD Primer](https://www.investopedia.com/articles/technical/082701.asp) is helpful
#### Actual Behaviour
Not the same as the TV in either of the cases above
#### Steps to Reproduce the Problem
MACD: 12/26/9 not-inverted
3 hour period
ETH/BTC
May5 @ 10:30 -> June2 @ 10:30
#### Specifications
 - Gimmer Version: 0.2.13
 - OS: Ubuntu 18.04
 - Date: 2 June 2018
 
#### Printscreen (Case needed)
![screenshot from 2018-06-02 11-09-53](https://user-images.githubusercontent.com/39344601/40873305-c46c6442-6655-11e8-9cce-ed3c642875bf.png)

MACD is green
Signal is yellow
Difference is red histogram

**Comment by swampibboy** [comment] 2018-06-02 11:44
duplicate of issue #34

**Comment by Flllexa** [comment] 2018-06-15 12:51
We separate customized settings and default, now if want run with Gimmer settings you need enable on checkbox, thanks

**Closed by Flllexa** 2018-06-15 12:51 UTC
Labels: Category: Backend, Platform: All, Priority : Medium, Status: Fixed/Pending Release, Type: Improvement
