### ISSUE TITLE
EMA cross Buy/Sell operations in backtest don't correlate with TradingView signals

### ISSUE THREAD

**Issue by ficovolante** [GimmerBot/Gimmer#50] opened 2018-05-19 21:34 UTC
Linux distro of Gimmer 0.2.11
Order type: market
Exchange: Binance
Pair: ETH/BTC
Interval: 30M
From: 05/11/2018 18:26
To: 05/19/2018 18:26
Default EMA Cross settings: 9/26 signal not inverted
![image](https://user-images.githubusercontent.com/39344601/40273211-2cddfc4a-5bb4-11e8-9359-1e5d3a9adb93.png)

There is one Buy and Sell in this portion of the backtest. They don't occur when the EMA's cross. There are many EMA cross points but no Buy/Sells are triggered. Perhaps Gimmer is using a different way to calculate the EMA than Tradingview. Looks like if Gimmer used Tradingview's EMA cross points, backtest would be more profitable (in this case).

**Comment by swampibboy** [comment] 2018-05-20 00:07
yes mate the issue is raised in #39 ,
you will find that not one of the indicators work as they are ment too yet

**Comment by Flllexa** [comment] 2018-05-26 22:17
Hello man, EMA Cross is fixed now, we already updated the dapp and will upload the release 0.2.12 soon, tks

**Closed by Flllexa** 2018-05-26 22:17 UTC
Labels: Status: Duplicate

**Comment by Drangla** [comment] 2018-06-05 17:17
Is the EMA Cross indicator inverted by default?(like the BB Indicator) can someone check this? 
It makes no sense to invert the signal by default when the Indicator´s work as they should. The bot will loose alomst every trade.

**Comment by Drangla** [comment] 2018-06-05 17:21
Sorry ... problem already solved... didnt see that.
